name: SonarCloud Analysis

on:
  push:
    branches: ["main", "lab8"]

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean compile

      - name: SonarCloud analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=reginaa11_lab_work \
            -Dsonar.organization=reginaa11 \
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}