name: Lab1 CI

on:
  push:
    branches: [ lab1 ]
  pull_request:
    branches: [ main, lab1 ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B compile

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Test Lab1 compilation
        run: |
          javac -d build src/main/java/com/example/lab1/HelloProgram.java
          echo "✅ Lab1 program compiles successfully"

      - name: Verify program output
        run: |
          cd src/main/java
          javac com/example/lab1/HelloProgram.java
          echo -e "TestUser" | java com.example.lab1.HelloProgram | grep -q "Hello, TestUser!"
          echo "✅ Program produces correct output"